'use client';
import { useEffect, useState } from 'react';
import { pointsDB, crmAnon } from '@/lib/supabase';

const MONTHS = ['January','February','March','April','May','June','July','August','September','October','November','December'];

export default function PaySlips({ dark, t }: { dark?: boolean, t?: any }) {
  const theme = t || { panel: '#161b22', panelBorder: '#21262d', text: '#e6edf3', subtext: '#8b949e', inputBg: '#0d1117', inputBorder: '#30363d', tableBorder: '#161b22' };
  const now = new Date();
  const [month, setMonth] = useState(now.getMonth());
  const [year, setYear] = useState(now.getFullYear());
  const [employees, setEmployees] = useState<any[]>([]);
  const [selected, setSelected] = useState<any>(null);
  const [perf, setPerf] = useState<any[]>([]);
  const [loading, setLoading] = useState(true);

  useEffect(() => { load(); }, [month, year]);

  const load = async () => {
    setLoading(true);
    const { data: emp } = await pointsDB.from('hr_employees').select('*').eq('is_active', true).order('name');
    const { data: p } = await crmAnon.rpc('get_telesales_leaderboard', { p_year: year, p_month: month + 1 });
    setEmployees(emp || []);
    setPerf(p || []);
    setLoading(false);
  };

  const getEmployeeData = (emp: any) => {
    const p = perf.find((p: any) => p.email === emp.email);
    const subs = p ? Number(p.subscription_count) : 0;
    const calls = p ? Number(p.answered_calls) : 0;
    const bonus = subs * Number(emp.bonus_per_sub);
    const net = Number(emp.base_salary) + bonus;
    return { subs, calls, bonus, net, points: p ? Number(p.monthly_points) : 0 };
  };

  const downloadPDF = async (emp: any) => {
    const { default: jsPDF } = await import('jspdf');
    const d = getEmployeeData(emp);
    const doc = new jsPDF();
    const monthName = MONTHS[month];

    // Header
    doc.setFillColor(13, 17, 23);
    doc.rect(0, 0, 210, 40, 'F');
    doc.setTextColor(88, 166, 255);
    doc.setFontSize(22);
    doc.setFont('helvetica', 'bold');
    doc.text('SHAMEL', 20, 20);
    doc.setTextColor(163, 113, 247);
    doc.text(' HR SYSTEM', 52, 20);
    doc.setTextColor(139, 148, 158);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.text('Pay Slip', 20, 30);
    doc.text(`${monthName} ${year}`, 20, 36);

    // Employee info
    doc.setTextColor(0, 0, 0);
    doc.setFontSize(14);
    doc.setFont('helvetica', 'bold');
    doc.text(emp.name, 20, 55);
    doc.setFontSize(10);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(100, 100, 100);
    doc.text(emp.email, 20, 63);
    doc.text(`Team: ${emp.team_name || 'N/A'}`, 20, 71);
    doc.text(`Hire Date: ${emp.hire_date || 'N/A'}`, 20, 79);

    // Divider
    doc.setDrawColor(200, 200, 200);
    doc.line(20, 85, 190, 85);

    // Performance
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Performance Summary', 20, 95);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text(`Subscriptions: ${d.subs}`, 20, 105);
    doc.text(`Answered Calls: ${d.calls}`, 20, 113);
    doc.text(`Total Points: ${d.points}`, 20, 121);

    // Earnings
    doc.line(20, 128, 190, 128);
    doc.setFontSize(11);
    doc.setFont('helvetica', 'bold');
    doc.setTextColor(0, 0, 0);
    doc.text('Earnings', 20, 138);
    doc.setFont('helvetica', 'normal');
    doc.setFontSize(10);
    doc.setTextColor(80, 80, 80);
    doc.text('Base Salary', 20, 148);
    doc.text(`EGP ${Number(emp.base_salary).toLocaleString()}`, 150, 148);
    doc.text(`Subscription Bonus (${d.subs} × EGP ${emp.bonus_per_sub})`, 20, 158);
    doc.setTextColor(63, 185, 80);
    doc.text(`+ EGP ${d.bonus.toLocaleString()}`, 150, 158);

    // Deductions
    doc.setTextColor(0, 0, 0);
    doc.line(20, 165, 190, 165);
    doc.setFont('helvetica', 'bold');
    doc.text('Deductions', 20, 175);
    doc.setFont('helvetica', 'normal');
    doc.setTextColor(80, 80, 80);
    doc.text('No deductions this month', 20, 185);

    // Net
    doc.line(20, 192, 190, 192);
    doc.setFillColor(13, 17, 23);
    doc.rect(20, 195, 170, 18, 'F');
    doc.setTextColor(255, 255, 255);
    doc.setFont('helvetica', 'bold');
    doc.setFontSize(12);
    doc.text('NET SALARY', 30, 207);
    doc.setTextColor(63, 185, 80);
    doc.text(`EGP ${d.net.toLocaleString()}`, 130, 207);

    // Footer
    doc.setTextColor(150, 150, 150);
    doc.setFontSize(8);
    doc.setFont('helvetica', 'normal');
    doc.text('Generated by Shamel HR System — Vezeeta Telesales', 20, 250);
    doc.text(`Generated on: ${new Date().toLocaleDateString()}`, 20, 257);

    doc.save(`payslip_${emp.name.replace(' ', '_')}_${monthName}_${year}.pdf`);
  };

  return (
    <div>
      <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '24px', flexWrap: 'wrap', gap: '12px' }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <svg width="24" height="24" viewBox="0 0 24 24" fill="none">
            <defs><linearGradient id="slg" x1="0%" y1="0%" x2="100%" y2="100%"><stop offset="0%" stopColor="#58a6ff"/><stop offset="100%" stopColor="#1f6feb"/></linearGradient></defs>
            <path d="M14 2H6a2 2 0 00-2 2v16a2 2 0 002 2h12a2 2 0 002-2V8z" stroke="url(#slg)" strokeWidth="2" strokeLinecap="round"/>
            <polyline points="14,2 14,8 20,8" stroke="url(#slg)" strokeWidth="2" strokeLinecap="round"/>
            <line x1="8" y1="13" x2="16" y2="13" stroke="url(#slg)" strokeWidth="2" strokeLinecap="round"/>
            <line x1="8" y1="17" x2="12" y2="17" stroke="url(#slg)" strokeWidth="2" strokeLinecap="round"/>
          </svg>
          <h1 style={{ fontSize: '1.5rem', fontWeight: '700' }}>Pay Slips</h1>
        </div>
        <div style={{ display: 'flex', gap: '10px' }}>
          <select value={month} onChange={e => setMonth(Number(e.target.value))} style={{ width: '140px', background: '#161b22', border: '1px solid #30363d', color: '#e6edf3', padding: '8px 12px', borderRadius: '8px', cursor: 'pointer' }}>
            {MONTHS.map((m, i) => <option key={m} value={i}>{m}</option>)}
          </select>
          <select value={year} onChange={e => setYear(Number(e.target.value))} style={{ width: '100px', background: '#161b22', border: '1px solid #30363d', color: '#e6edf3', padding: '8px 12px', borderRadius: '8px', cursor: 'pointer' }}>
            {[2025, 2026].map(y => <option key={y} value={y}>{y}</option>)}
          </select>
        </div>
      </div>

      <div style={{ display: 'grid', gridTemplateColumns: selected ? '1fr 1fr' : '1fr', gap: '20px' }}>
        {/* Employee List */}
        <div className="glass-panel">
          <div style={{ padding: '12px 20px', borderBottom: '1px solid #21262d', fontWeight: '600' }}>
            Select Employee to Generate Pay Slip
          </div>
          {loading ? (
            <div style={{ textAlign: 'center', padding: '40px', color: '#8b949e' }}>Loading...</div>
          ) : (
            <div>
              {employees.map((e) => {
                const d = getEmployeeData(e);
                return (
                  <div key={e.id} onClick={() => setSelected(e)} style={{
                    padding: '14px 20px', borderBottom: '1px solid #161b22', cursor: 'pointer',
                    background: selected?.id === e.id ? 'rgba(88,166,255,0.08)' : 'transparent',
                    borderLeft: selected?.id === e.id ? '3px solid #58a6ff' : '3px solid transparent',
                    display: 'flex', justifyContent: 'space-between', alignItems: 'center',
                    transition: 'all 0.2s',
                  }}>
                    <div>
                      <div style={{ fontWeight: '600', fontSize: '0.9rem' }}>{e.name}</div>
                      <div style={{ color: '#8b949e', fontSize: '0.75rem', marginTop: '2px' }}>{e.team_name || 'No team'}</div>
                    </div>
                    <div style={{ textAlign: 'right' }}>
                      <div style={{ color: '#3fb950', fontWeight: '700', fontSize: '0.9rem' }}>EGP {d.net.toLocaleString()}</div>
                      <div style={{ color: '#8b949e', fontSize: '0.72rem' }}>{d.subs} subs · {d.calls} calls</div>
                    </div>
                  </div>
                );
              })}
            </div>
          )}
        </div>

        {/* Pay Slip Preview */}
        {selected && (() => {
          const d = getEmployeeData(selected);
          return (
            <div className="glass-panel" style={{ padding: '24px' }}>
              <div style={{ display: 'flex', justifyContent: 'space-between', alignItems: 'center', marginBottom: '20px' }}>
                <div style={{ fontWeight: '700', fontSize: '1rem' }}>Pay Slip Preview</div>
                <button onClick={() => downloadPDF(selected)} style={{ padding: '8px 20px', background: 'linear-gradient(135deg, #58a6ff, #1f6feb)', color: 'white', border: 'none', borderRadius: '8px', fontWeight: '600', cursor: 'pointer', fontSize: '0.875rem' }}>
                  ⬇ Download PDF
                </button>
              </div>

              {/* Header */}
              <div style={{ background: '#0d1117', borderRadius: '8px', padding: '16px', marginBottom: '16px', display: 'flex', justifyContent: 'space-between' }}>
                <div>
                  <div style={{ fontWeight: '800', fontSize: '1.1rem', background: 'linear-gradient(135deg, #58a6ff, #a371f7)', WebkitBackgroundClip: 'text', WebkitTextFillColor: 'transparent', backgroundClip: 'text' }}>SHAMEL HR</div>
                  <div style={{ color: '#8b949e', fontSize: '0.72rem', marginTop: '2px' }}>PAY SLIP</div>
                </div>
                <div style={{ textAlign: 'right' }}>
                  <div style={{ fontWeight: '600' }}>{MONTHS[month]} {year}</div>
                  <div style={{ color: '#8b949e', fontSize: '0.75rem' }}>{selected.team_name}</div>
                </div>
              </div>

              {/* Employee */}
              <div style={{ marginBottom: '16px' }}>
                <div style={{ fontWeight: '700', fontSize: '1.1rem' }}>{selected.name}</div>
                <div style={{ color: '#8b949e', fontSize: '0.8rem' }}>{selected.email}</div>
              </div>

              {/* Performance */}
              <div style={{ background: '#0d1117', borderRadius: '8px', padding: '12px 16px', marginBottom: '16px', display: 'flex', gap: '24px' }}>
                <div><div style={{ color: '#8b949e', fontSize: '0.72rem' }}>Subscriptions</div><div style={{ color: '#3fb950', fontWeight: '700', fontSize: '1.1rem' }}>{d.subs}</div></div>
                <div><div style={{ color: '#8b949e', fontSize: '0.72rem' }}>Calls</div><div style={{ color: '#58a6ff', fontWeight: '700', fontSize: '1.1rem' }}>{d.calls}</div></div>
                <div><div style={{ color: '#8b949e', fontSize: '0.72rem' }}>Points</div><div style={{ color: '#a371f7', fontWeight: '700', fontSize: '1.1rem' }}>{d.points}</div></div>
              </div>

              {/* Breakdown */}
              {[
                { label: 'Base Salary', value: `EGP ${Number(selected.base_salary).toLocaleString()}`, color: '#e6edf3' },
                { label: `Subscription Bonus (${d.subs} × EGP ${selected.bonus_per_sub})`, value: `+ EGP ${d.bonus.toLocaleString()}`, color: '#3fb950' },
                { label: 'Deductions', value: 'EGP 0', color: '#f85149' },
              ].map((row, i) => (
                <div key={i} style={{ display: 'flex', justifyContent: 'space-between', padding: '10px 0', borderBottom: '1px solid #21262d', fontSize: '0.875rem' }}>
                  <span style={{ color: '#8b949e' }}>{row.label}</span>
                  <span style={{ color: row.color, fontWeight: '600' }}>{row.value}</span>
                </div>
              ))}

              {/* Net */}
              <div style={{ marginTop: '12px', background: '#0d1117', borderRadius: '8px', padding: '16px', display: 'flex', justifyContent: 'space-between', alignItems: 'center', border: '1px solid rgba(63,185,80,0.3)' }}>
                <span style={{ fontWeight: '700', fontSize: '1rem' }}>NET SALARY</span>
                <span style={{ fontWeight: '900', fontSize: '1.3rem', color: '#3fb950' }}>EGP {d.net.toLocaleString()}</span>
              </div>
            </div>
          );
        })()}
      </div>
    </div>
  );
}
